### ISSUE TITLE
Problems with Jest + Storybook

### ISSUE THREAD

**Issue by ppalmeida** [dmtrKovalenko/material-ui-pickers#575]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  v1.0.0-rc.12     |
| material-ui         |   ^1.2.1      |
| React               |    16.4.1     |
| Browser             |    terminal     |
| Platform            |   OSX 10.12 Sierra      |
| Peer library        |    moment     | 

## Steps to reproduce
1. Create a simple component
2. Create a storybook and use Jest snapshot
3. Run jest test

## Expected behavior
That the test pass without any errors from DatePicker or DateTimePicker

## Actual behavior
There are many errors related to DatePicker and DateTimePicker.

● APP/JobsList/CreateJobComponent › CreateNewJob closed and empty

    TypeError: utils.date is not a function
      
      at getInitialDate (node_modules/material-ui-pickers/_shared/BasePicker.js:28:58)
      at new WithState (node_modules/recompose/withState.js:52:60)
      at constructClassInstance (node_modules/react-dom/cjs/react-dom.development.js:11447:18)
      at updateClassComponent (node_modules/react-dom/cjs/react-dom.development.js:13144:7)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:13824:14)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:15863:12)
      at workLoop (node_modules/react-dom/cjs/react-dom.development.js:15902:24)
      at renderRoot (node_modules/react-dom/cjs/react-dom.development.js:15942:7)
      at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:16560:22)
      at performWork (node_modules/react-dom/cjs/react-dom.development.js:16482:7)
      at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:16454:3)
      at requestWork (node_modules/react-dom/cjs/react-dom.development.js:16354:5)
      at scheduleWork$1 (node_modules/react-dom/cjs/react-dom.development.js:16218:11)
      at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:16785:3)
      at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:16812:10)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:16839:10)
      at ReactRoot.Object.<anonymous>.ReactRoot.render (node_modules/react-dom/cjs/react-dom.development.js:17122:3)
      at node_modules/react-dom/cjs/react-dom.development.js:17262:14
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:16679:10)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:17258:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:17317:12)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:218:50)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:98:16)
      at mount (node_modules/enzyme/build/mount.js:19:10)
      at Object.<anonymous> (src/packages/visto-web-test-utils/src/storyshot.js:17:34)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

And:

     The above error occurred in the <BasePicker> component:
        in BasePicker (created by Consumer)
        in Consumer (created by WithUtils(BasePicker))
        in WithUtils(BasePicker) (created by DateTimePickerWrapper)
        in DateTimePickerWrapper (created by WithStyles(DateTimePickerWrapper))
        in WithStyles(DateTimePickerWrapper) (created by ForwardRef)
        in div (created by Grid)
        in Grid (created by WithStyles(Grid))
        in WithStyles(Grid) (at CreateNewJob.js:194)
        in div (created by Grid)
        in Grid (created by WithStyles(Grid))
        in WithStyles(Grid) (at CreateNewJob.js:192)
        in div (created by Grid)
        in Grid (created by WithStyles(Grid))
        in WithStyles(Grid) (at CreateNewJob.js:189)
        in div (created by Grid)
        in Grid (created by WithStyles(Grid))
        in WithStyles(Grid) (at CreateNewJob.js:179)
        in form (at CreateNewJob.js:142)
        in div (created by Grid)
        in Grid (created by WithStyles(Grid))
        in WithStyles(Grid) (at InsetContentHolder.js:57)
        in div (created by Grid)
        in Grid (created by WithStyles(Grid))
        in WithStyles(Grid) (at InsetContentHolder.js:52)
        in InsetContentHolder (created by WithStyles(InsetContentHolder))
        in WithStyles(InsetContentHolder) (at CreateNewJob.js:140)
        in CreateNewJob (created by WithStyles(CreateNewJob))
        in WithStyles(CreateNewJob) (at CreateNewJob.stories.js:180)
        in WrapStory
        in div
        in div (at setupTests.js:38)
        in Provider (at TooltipProvider.js:40)
        in TooltipProvider
        in div (at setupTests.js:38)
        in Provider (created by MuiPickersUtilsProvider)
        in MuiPickersUtilsProvider
        in MuiThemeProvider
        in JssProvider (created by WrapperComponent)
        in WrapperComponent
    

In my `~/.storybook/config.js` file I already added the `MuiPickersUtilsProvider` and `MomentUtils` as `utils` property, so Storybook works fine with my components. 

But then I use Storybook states to generate Jest snapshots in my tests, and, when Jest runs the test, I think Jest is not prepared to shallow DatetimePicker - because it needs the `utils.date` thing. Is there any quick solution so i can keep my component's test? Should I import anything in my tests setUp?

**Comment by dmtrKovalenko** [comment]
you need to add `MuiUtilsProvider` outside all the pickers. Its required to have react context outside of each picker. So you need to add it globally if its possible.
